// jest-dom adds custom jest matchers for asserting on DOM nodes.
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
// learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom';

const d = {
    "allocationNumber": "234324",
    "amount": "4600000",
    "assignedTo": {
        "age": "",
        "contactAddress": "ibandon street ",
        "contactName": "eggman",
        "contactPhone": "08044554433",
        "dob": "2004-11-17",
        "email": "bankiakid@gmail.com",
        "firstname": "EDDY",
        "gender": "M",
        "lastname": "JAMES",
        "nationality": "Nigerian",
        "nin": "34556543454",
        "ownershipType": "PRIVATE",
        "phone": "08033443322",
        "residentialAddress": "garki 2",
        "stateOfOrigin": 26,
        "title": ""
    },
    "cofoNumber": "76567",
    "commencementDate": "2023-03-16",
    "dateOfExpiration": "2023-04-15",
    "executionDate": "2023-04-10",
    "landSize": "vv",
    "landType": "Flat",
    "landUse": "Commercial",
    "lastPaymentDate": "2023-04-05",
    "legalDescription": "avadvfsadvbfs",
    "lengthOfTerm": "99",
    "lga": 1,
    "parcelNumber": "rre",
    "paymentOfMethod": "bank",
    "regDate": "2023-03-16",
    "regPage": "1",
    "regTime": "12:45",
    "registrationNumber": "345432",
    "rentRate": "4000",
    "rentRevision": "90",
    "rofoNumber": "234543",
    "surveyDate": "2023-04-04",
    "surveyDesignation": "av fadv",
    "surveyPlanNumber": "345",
    "surveyorGeneralDate": "2023-04-07",
    "surveyorName": "bsvadfs",
    "timeOfErection": "12:34",
    "valueOfImprovement": "bsbsbf",
    "volumeNo": "2"
};


const newDATA = {
    "parcelNumber": "001",
    "landSize": 56.78,
    "landUse": "Agriculture",
    "landType": "fland land",
    "legalDescription": "Not available",
    "lga": 1,
    "lastPaymentDate": "2020-01-01",
    "amount": 34.90,
    "paymentOfMethod": "Bank",
    "surveyPlanNumber": "009",
    "surveyDate": "2020-01-01",
    "surveyDesignation": "Director",
    "surveyorName": "Akaramuda",
    "surveyorGeneralDate": "2020-01-01",
    "allocationNumber": "009",
    "rofoNumber": "09999",
    "lengthOfTerm": 99,
    "rentRate": 90.99,
    "commencementDate": "2020-01-01",
    "rentRevision": "uuuu",
    "timeOfErection": "11:89",
    "valueOfImprovement": 89.99,
    "cofoNumber": "90999",
    "executionDate": "2020-01-01",
    "dateOfExpiration": "",
    "registrationNumber": "567856789",
    "regPage": 1,
    "volumeNo": "09999",
    "regDate": "",
    "regTime": "11:90",
    "assignedTo": {
        "name": "INC Company",
        "registrationNumber": "5678765",
        "registrationAddress": "Arab road",
        "registrationDate": "",
        "residentialAddress": "residentialAddress",
        "contactAddress": "contactAddress",
        "phone": "phone",
        "email": "email",
        "officeAddress": "no 23 off upper iweka",
        "ownershipType": "CORPORATE",
        "nationality": "Nigeria",
        "contactPhone": "09088667755",
        "contactName": "Omenesa Muhammed Z",
        "tin": "4567899876567890",
        "faxNumber": "787879",
        "correspondence": "correspondence",
        "typeOfBusiness": "demand and suppply"
    }
}